#.travis.yml

language: node_js
node_js:
  - 10
cache: npm

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools

script:
  - npm run build

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: '$FIREBASE_TOKEN'
  project: 'the-evergreen-dev'
